Class Treinamento.Teste2 Extends %Persistent
{

Storage Default
{
<Data name="Teste2DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Treinamento.Teste2D</DataLocation>
<DefaultData>Teste2DefaultData</DefaultData>
<IdLocation>^Treinamento.Teste2D</IdLocation>
<IndexLocation>^Treinamento.Teste2I</IndexLocation>
<StreamLocation>^Treinamento.Teste2S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
